### ISSUE TITLE
Link to my solution

### ISSUE THREAD

**Issue by renestadler** [htl-perg-2018-19-4bhif/angular-todo-example-renestadler#1]
You'll find my version of the TODO-List behind the Link below
[https://bit.ly/2OxjIBY](https://bit.ly/2OxjIBY)

**Comment by rstropek** [comment]
Nice 👍, works as expected. Two extra points are yours.

Greetings,
Rainer Stropek

**Comment by rstropek** [comment]
Nice 👍, works as expected. Two extra points are yours.

Greetings,
Rainer Stropek
